require('lualine').setup({
    -- tabline = {
    --     lualine_a = {
    --         {
    --             'buffers',
    --             max_length = function()
    --                 return vim.o.columns / 3 * 2
    --             end,
    --             mode = 2,
    --         }
    --     },
    --     -- lualine_b = {},
    --     -- lualine_c = {},
    --     -- lualine_x = {},
    --     -- lualine_y = {},
    --     lualine_z = {
    --         {
    --             'tabs',
    --             max_length = function()
    --                 return vim.o.columns / 3
    --             end,
    --             mode = 0,
    --         }
    --     }
    -- }
})
